name: Warden Command Issue
description: Report an issue with the Warden software (e.g. `warden` commands, docker compose files, images not pulling or mutagen sync)
title: '[Command] '
labels: bug
body:
  - type: input
    id: version
    attributes:
      label: Version of Warden
      description: Run `warden version` and provide the output
      placeholder: warden version
    validations:
      required: true
  - type: input
    id: install
    attributes:
      label: Operating System and Installation Method
      description: Please tell us how you installed Warden and on what operating system.  (E.g. "Mac OS 12.6 via Brew")
      placeholder: Mac OS 12.6 via Brew
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      value: |
        1. Go to '...'  
        2. Click on '....'  
        3. Scroll down to '....'  
        4. See error
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen and when
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
