version: "3.5"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.rule=Host(`portainer.${WARDEN_SERVICE_DOMAIN:-den.test}`)||Host(`portainer.warden.test`)
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      # Enable basic auth, set var in ~/.warden/.env
    #      - "traefik.http.middlewares.portainer-auth.basicauth.users=${WARDEN_BASICAUTH_USER}:${WARDEN_BASICAUTH_PASS}"
    #      - "traefik.http.routers.portainer.middlewares=portainer-auth"
    restart: ${WARDEN_RESTART_POLICY:-always}