---
api:
  dashboard: true
providers:
  #  file:
  #    filename: /etc/traefik/dynamic.yml
  docker:
    network: warden
    defaultRule: "Host(`{{ .Name }}.warden.test`)"
    exposedByDefault: false
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
log:
  level: info
global:
  checkNewVersion: false
  sendAnonymousUsage: false

certificatesResolvers:
  letsencrypt:
    acme:
      tlsChallenge: {}
      email: "shakhmehedi@rezolve.com"
      # Staging
      #caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      #storage: "/etc/ssl/certs/letsencrypt-staging.json"
      # production
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      storage: "/etc/ssl/certs/letsencrypt-prod.json"
